import { addPost } from "../api";

// Auto-generated blog post loader
// This file is automatically generated by scripts/generate-blog-loader.mjs
// Do not edit manually - your changes will be overwritten

const example_post = `---
title: My First Blog Post
date: 2025-10-27
description: An example blog post showing the MDX format
---

# Hello World

This is an example blog post written in **MDX** with frontmatter.

You can use all standard markdown features here.`;

const getting_started = `---
title: Getting Started with PrestonOS
date: 2025-10-29
description: Learn how to use PrestonOS
---

# Welcome to PrestonOS

PrestonOS is a modern, web-based operating system.

## Key Features

- **Window Management**: Drag, resize, and manage multiple windows
- **Built-in Apps**: Notes, Blog, and more
- **Extensible**: Easy to add new applications

## Getting Started

Simply open any app from the dock to begin exploring!`;

const hello_world = `---
title: Hello World
date: 2025-11-06
description: A test blog post using gray-matter
tags:
  - test
  - blog
---

# Hello World

This is a test blog post that uses **gray-matter** for frontmatter parsing.`;

// Load all posts
addPost("example-post", example_post);
addPost("getting-started", getting_started);
addPost("hello-world", hello_world);
